os: windows
language: shell

env:
  global:
    - GOVERSION: 1.12.10
    - NODEJS_VERSION: 11.14.0

before_install:
  - git clone https://github.com/portapps/portapps ${TRAVIS_BUILD_DIR}/../portapps
  - source ${TRAVIS_BUILD_DIR}/../portapps/.travis/prepare.sh
  - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/java.sh
  - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/ant.sh
  - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/nodejs.sh
  - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/go.sh

script:
  - ant release

after_success:
  - export APP_VERSION=$(cat $TRAVIS_BUILD_DIR/bin/tmp/version.dat)
  - echo ${APP_VERSION}

before_deploy:
  - git config --local user.email "builds@travis-ci.com"
  - git config --local user.name "Travis CI"
  - export TRAVIS_TAG="${APP_VERSION}"
  - git tag $TRAVIS_TAG
  - ls -al bin/release

deploy:
  provider: releases
  api_key:
    secure: Nj6dugIKJonuI9BuIR25NJN31NdvAPFHMq8Lp6/OMwFv2jeHSac7ay3Lz79pfMqHX8crH+2jdQamyALzb52LIjOKWI/5f8++uyzefC/Xwts9Wr1vhkJzH9Urr0X1J6oL3uoTqGsNmv33jYcgP0cwB4D8A4blvNZ+K8n4XDMm4B6wK1Y6hOWGFx/1J88Tie6YO64/O4P7wZoRm+lLeaIAxbR6IoaZlXTkFnd5HPz0u/iovNo6pTkedtuvrxRAuqAIYug3PJcUsYzs/uxE2IMz6wZwvM9102oe3DH5CxIOL3V/bcc8/DSNIvrZsQjZEcri9B9cz+fjY6EMWxdo9w2N1p7TYahhnG/vHDyH2nb9Tuwmg7VuNWK9d1PAjDlG8X8VUsNcR08kD2XLzKJ0xJhnRioRPyh4KCdn62akdioJblX/P/a1n1r4uEu+wn16f7Zr3Fy5PcexOArrJQ8qn6zTiug05gV57a2ZjfHJHKl72Lf6MH1/Wy6JHEOBsD1/RsPAHhOpioSFLTD/lGZjQm+GGAAW8xzedV11A0z4yro0H9eJnmaw34zFTNPyri0DsOIhg7mdu6iO5uutSfZwAmTBRV8ich0fxYQP7R4y9chVTBgsoenr8WMZh3qQTexgRUsMCI4eFpZEsqCZgRPL2gSvwAvtbOhkgM3lVz+TVg3gkN4=
  file_glob: true
  file: bin/release/*
  skip_cleanup: true
  draft: true
  on:
    tags: false

notifications:
  email:
    recipients:
      - travisci@portapps.io
    on_success: always
    on_failure: always
